// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkwkicgtjvibczyklcyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrd2tpY2d0anZpYmN6eWtsY3lnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyNTg1OTAsImV4cCI6MjA1NjgzNDU5MH0.ur3-VCo_kan9qaFrpJSXmPRo_NfLfva5vp2Ca5pvj0c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);